### ISSUE TITLE
将 termux.md 翻译为英文

### ISSUE THREAD

**Issue by ywh555hhh** [hust-open-atom-club/hust-mirrors#101]
描述：
termux.md 提供了有关 Termux 的信息，这是一个基于 Android 的 Linux 仿真应用，可在手机上运行 Linux。英文版本将对 Android 用户和对移动 Linux 有兴趣的开发者有所帮助。

目标：
将 termux.md 翻译为英文。

**Comment by THINKER-ONLY** [comment]
I want to try it!
