### ISSUE TITLE
写一篇 blog 说明一下 ubuntukylin-image

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/hust-mirrors#110]
大致内容：

因 cdimage.ubuntukylin.com 域名失效导致 ubuntukylin-image 镜像无法正常同步，故暂停 ubuntukylin 镜像的同步，直到社区发布新的下载镜像源站。

**Comment by jingfelix** [comment]
感觉还好，一是上游（源站，TUNA）也没做解释；二是即使暂停，对cdimage的下载也能正常用。

**Comment by mudongliang** [comment]
第一，这个blog的重点是在于我们暂停了这个镜像源的同步，上游没做任何操作，肯定不需要解释。第二，暂定之后，cdimage的内容已经不是最新了
