### ISSUE TITLE
🚨 lint: Markdown writing standards for `zhlint`

### ISSUE THREAD

**Issue by M0rtzz** [hust-open-atom-club/hust-mirrors#120]
- Docs
  - [x] [cli-tool.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/cli-tool.md) {log: [cli-tool.md.log](https://github.com/user-attachments/files/17941963/cli-tool.md.log)}
  - [x] [CPAN.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/CPAN.md) {log: [CPAN.md.log](https://github.com/user-attachments/files/17941964/CPAN.md.log)}
  - [x] [CRAN.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/CRAN.md) {log: [CRAN.md.log](https://github.com/user-attachments/files/17941965/CRAN.md.log)}
  - [x] [crates.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/crates.md) {log: [crates.md.log](https://github.com/user-attachments/files/17941966/crates.md.log)}
  - [x] [CTAN.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/CTAN.md) {log: [CTAN.md.log](https://github.com/user-attachments/files/17941967/CTAN.md.log)}
  - [x] [deepin.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/deepin.md) {log: [deepin.md.log](https://github.com/user-attachments/files/17941968/deepin.md.log)}
  - [x] [gnu.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/gnu.md) {log: [gnu.md.log](https://github.com/user-attachments/files/17941948/gnu.md.log)}
  - [x] [golang.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/golang.md) {log: [golang.md.log](https://github.com/user-attachments/files/17941949/golang.md.log)}
  - [x] [linuxmint.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/linuxmint.md) {log: [linuxmint.md.log](https://github.com/user-attachments/files/17941950/linuxmint.md.log)}
  - [x] [linux-next.git.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/linux-next.git.md) {log: [linux-next.git.md.log](https://github.com/user-attachments/files/17941951/linux-next.git.md.log)}
  - [x] [llvm-project.git.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/llvm-project.git.md) {log: [llvm-project.git.md.log](https://github.com/user-attachments/files/17941952/llvm-project.git.md.log)}
  - [ ] [openeuler.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/openeuler.md) {log: [openeuler.md.log](https://github.com/user-attachments/files/17941953/openeuler.md.log)}
  - [ ] [openkylin.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/openkylin.md) {log: [openkylin.md.log](https://github.com/user-attachments/files/17941954/openkylin.md.log)}
  - [ ] [qemu.git.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/qemu.git.md) {log: [qemu.git.md.log](https://github.com/user-attachments/files/17941957/qemu.git.md.log)}
  - [ ] [rustup.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/rustup.md) {log: [rustup.md.log](https://github.com/user-attachments/files/17941958/rustup.md.log)}
  - [ ] [termux.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/termux.md) {log: [termux.md.log](https://github.com/user-attachments/files/17941959/termux.md.log)}
  - [ ] [ubuntukylin.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/ubuntukylin.md) {log: [ubuntukylin.md.log](https://github.com/user-attachments/files/17941961/ubuntukylin.md.log)}
  - [ ] [ubuntu.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/ubuntu.md) {log: [ubuntu.md.log](https://github.com/user-attachments/files/17941960/ubuntu.md.log)}
  - [ ] [virtualbox.md](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/docs/virtualbox.md) {log: [virtualbox.md.log](https://github.com/user-attachments/files/17941962/virtualbox.md.log)}

**Comment by tttturtle-russ** [comment]
这个列表可能需要重新lint之后更新一下
