### ISSUE TITLE
Fix the bracket issue of zhLint CI

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/hust-mirrors#124]
zhlint 默认要求括号都是半角，全角都会触发warning，可以通过 .zhlintrc 来进行设置

**Comment by mudongliang** [comment]
如果只是一行或很短的话，我个人建议直接用 echo "XXX" > .zhlintrc
否则，放在我们仓库中，比如ci这个目录

**Comment by mudongliang** [comment]
@tttturtle-russ 浩阳，你有时间处理一下这个问题吗？这样你之前那个PR就可以搞定了

**Comment by tttturtle-russ** [comment]
我来研究研究这个配置

**Comment by mudongliang** [comment]
#125
