### ISSUE TITLE
把我们镜像站点加入到linuxmint, archlinux等发行版的站点选择列表里面

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/hust-mirrors#13]
当然，这个事情需要外网开通之后做

**Comment by Souls-R** [comment]
- [ ] termux的镜像站点的选择列表 https://github.com/termux/termux-tools/issues

**Comment by tttturtle-russ** [comment]
TODO:
- [ ] archlinux https://gitlab.archlinux.org/archlinux/arch-mirrors
- [ ] linuxmint https://linuxmint.com/mirrors.php
- [ ] blackarch https://github.com/BlackArch/blackarch
- [ ] Ubuntu https://launchpad.net/ubuntu/+newmirror
- [ ] archlinuxcn https://github.com/archlinuxcn/mirrorlist-repo

**Comment by mudongliang** [comment]
@tttturtle-russ @Souls-R @EarthCompass @jxlpzqc 我们后续的计划可以开始了

**Comment by tttturtle-russ** [comment]
> 根据其[页面](https://mirrors.alpinelinux.org/)的说明，Alpine Linux 添加到镜像列表的方式是发送邮件到 [alpine-mirrors@alpinelinux.org](mailto:alpine-mirrors@alpinelinux.org)

谢谢，邮件已发送。

**Comment by mudongliang** [comment]
Openkylin已经将我们加入对方的镜像列表中<https://www.openkylin.top/downloads/mirrors-en.html>

**Comment by mudongliang** [comment]
我又给alphine和linuxmint发了邮件，如果对方还是没有什么回复的话，那就算了

**Comment by mudongliang** [comment]
linuxmint 就算了，不管对方了，该issue可以关闭了
