### ISSUE TITLE
参考Debian帮助文档格式编写UbuntuKylin帮助文档

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/hust-mirrors#24]

**Comment by mudongliang** [comment]
[ubuntukylin-cdimage](https://mirrors.hust.edu.cn/ubuntukylin-cdimage) 软件源的描述要加入到ubuntukylin的帮助文档中，并使用anchor ID来进行链接

**Comment by jxlpzqc** [comment]
已完成，close该issue
