### ISSUE TITLE
VirtualBox 帮助文档 Bug

### ISSUE THREAD

**Issue by mudongliang** [hust-open-atom-club/hust-mirrors#25]
这些文件路径，我们都没有，所以访问肯定会出错。这种应该是同步完成之后做的额外动作，因为上游好像也没有。

<img width="899" alt="截屏2024-03-27 09 27 46" src="https://github.com/hust-open-atom-club/hust-mirrors/assets/6214861/8a77584a-c4ab-4596-b851-6b9fbcdeab52">

**Comment by jxlpzqc** [comment]
是的

https://github.com/tuna/tunasync-scripts/blob/fb7d162b8b7be44af9b5aec72751c32a9a1f9951/virtualbox.sh#L87-L99

**Comment by jxlpzqc** [comment]
我认为直接链接到我们的下载页(/release)就行

**Comment by mudongliang** [comment]
我觉得可以的，我们没必要跟他们完全一致

**Comment by jxlpzqc** [comment]
fix in c64c2922d7633639c1ab0dd51eb1c4588ef46819
