### ISSUE TITLE
滚动条控件滚动时不连续

### ISSUE THREAD

**Issue by SophieTwilight** [hust-open-atom-club/hust-mirrors#32]
镜像站的滚动条控件在向下滚动到接近底部（一般为倒数第五个），以及向上滚动到接近顶部（一般为正数第五个）时，会突然跳转至底部或顶部，对用户不是很友好。

https://github.com/hust-open-atom-club/hust-mirrors/assets/53810827/1ae23e15-4ca0-490a-a72a-0820a77b5d7b

**Comment by jxlpzqc** [comment]
我使用 firefox 124 和 edge 123 均无法复现该情况

**Comment by SophieTwilight** [comment]
windows 下 firefox 没有问题，chrome 123 症状轻微，edge 123 较为严重

上游也存在该问题，暂不考虑修复
