### ISSUE TITLE
[Feature] [发行版下载] 支持 msys2 

### ISSUE THREAD

**Issue by jxlpzqc** [hust-open-atom-club/hust-mirrors#79]
任务描述：在镜像站的 [发行版下载页面](https://mirrors.hust.edu.cn/release/) 中支持 msys2 的下载
1. 学习正则表达式用法
2. 观察 [msys 源](https://mirrors.hust.edu.cn/msys2) 的目录结构，找到安装包的位置
3. 参考 [ci/releases.conf](https://github.com/hust-open-atom-club/hust-mirrors/blob/master/ci/releases.conf) 中的已有内容，增加一个条目，并编写一个表达式，使得其可以匹配 第二步找到的安装包路径。

[附] 正则表达式调试工具：https://regex101.com/

**Comment by mudongliang** [comment]
功能已经完成，关闭 issue

![image](https://github.com/user-attachments/assets/1ab2b889-7ca6-4270-af65-5abe3d0ee7e7)
