### ISSUE TITLE
[Task] docusaurus 3 适配

### ISSUE THREAD

**Issue by jxlpzqc** [hust-open-atom-club/hust-mirrors#8]
docusaurus 上游已经更新到3，升级到上游最新版，可以获得最新的特性，以及bug修复。

但是不像 docusaurus 2 中的 mdx 1，docusaurus  3 采用 mdx3 作为 markdown 编译器。除此以外，还引入了一些breaking change。

由于该镜像站Swizzling部分以及部分文档的原因，无法无缝升级到docusaurus 3，需要进行一些适配工作。

**Comment by zonewancheng** [comment]
https://github.com/hust-open-atom-club/hust-mirrors/pull/59
升级了一下，还遗留一些问题

**Comment by jxlpzqc** [comment]
#84
