### ISSUE TITLE
请求添加Anaconda镜像

### ISSUE THREAD

**Issue by horrordor** [hust-open-atom-club/hust-mirrors#92]
"conda"作为主流跨平台包管理工具，提供对python等编程工具和库的更轻松访问，在华科校内和校外都有广泛使用。因为gfw导致其官方源连通性存在问题，能否提供对Anaconda镜像以便利同学呢？

**Comment by mudongliang** [comment]
[mirrorrequest 仓库 #2](https://github.com/hust-open-atom-club/mirrorrequest/issues/2)
