### ISSUE TITLE
将 pypi.md 翻译为英文

### ISSUE THREAD

**Issue by ywh555hhh** [hust-open-atom-club/hust-mirrors#97]
描述：
pypi.md 介绍了 PyPI，这是 Python 的官方包管理库，对 Python 学习者和开发者非常重要。翻译为英文将帮助非中文用户了解如何使用和操作 PyPI。

目标：
将 pypi.md 翻译为英文。

**Comment by SXP-Simon** [comment]
Please assign this to me,I want to have a try.🙏🏻🙏🏻

**Comment by SXP-Simon** [comment]
emmm...sorry for my mistaken unassigning performance.but i think it's okay now to close this issue because it has been done.🙏🏻🙏🏻thanks for this chance and your joint efforts.

**Comment by mudongliang** [comment]
It's fine and the issue is closed. Oh, one best practice: we should link this issue with your PR so that github could close this issue automatically when your PR is merged.
