### ISSUE TITLE
 将 linuxmint.md 翻译为英文

### ISSUE THREAD

**Issue by ywh555hhh** [hust-open-atom-club/hust-mirrors#98]
描述：
linuxmint.md 文档介绍了 Linux Mint，这是一个易于上手的 Linux 发行版，特别适合初学者。翻译为英文将帮助全球范围内对 Linux 感兴趣的用户更好地了解这一系统。

目标：
提供 linuxmint.md 的英文版本。

**Comment by orchiddell0** [comment]
I eager to try it!

**Comment by orchiddell0** [comment]
I am eager to try it!
