### ISSUE TITLE
将 archlinuxcn.md 翻译为英文

### ISSUE THREAD

**Issue by ywh555hhh** [hust-open-atom-club/hust-mirrors#99]
描述：
archlinuxcn.md 文档介绍了 Arch Linux CN，这是 Arch Linux 在中国的一个非官方社区。将其翻译为英文可以帮助 Arch Linux 用户了解该社区及其资源。

目标：
创建 archlinuxcn.md 的英文版本。

**Comment by CAICAIIs** [comment]
I can try！
